spring.application.name=BootApp04-DataInjection-UsingValueAnnotation

#Diagnostic Center Catalog
dc.xrayRate = 1000
dc.ctscanRate = 3000
dc.mriscanRate = 10000
dc.ecgRate = 600

#Patient information
pi.name = Rajesh
pi.addr = Hydrabad
pi.mobileNo = 8574964151

