spring.application.name=BootApp06-ConfigurationPropetiesOnArray-List-Set-Has-AProperty

#Employee Info
#simple properties
#<prefix>.<property> = <value>
org.nit.eno = 101
org.nit.ename = Rajesh

#Array property
#<prefix>.<property>[index] = <value>
# here while speciying indext sequence matter 
org.nit.favColors[0] = red
org.nit.favColors[1] = blue
org.nit.favColors[2] = black
#org.nit.favColors[4] = green  -> invalid index - wrong gives exception

# or 

#org.nit.favColors = red,blue,black # -> [ inline systax ] 

#Collection properties
#list,set
#<prefix>.<property>[index] = <value>

#list
#org.nit.nickNames[0] = bunty
#org.nit.nickNames[1] = chintu
#org.nit.nickNames[2] = chhotu

# or , Inline systax
org.nit.nickNames = bunty,chintu,chhotu

#set
org.nit.phoneNumbers[0] = 123456789
org.nit.phoneNumbers[1] = 333333333
org.nit.phoneNumbers[2] = 345621341
# below will ingnore becuase dosent not support duplicate
org.nit.phoneNumbers[3] = 345621341  

# or , Inline systax
#org.nit.phoneNumbers = 123456789,333333333, 345621341, 345621341

#Map
#<prefix>.<property>.<subgruop/key> = <value>
org.nit.idDetails.aadharId = AABB244545
org.nit.idDetails.voterId = BJVJB123
org.nit.idDetails.passportno = IND9907123

#Has-A property
#<prefix>.<property>.<sub-property> = <value>
org.nit.company.id = 1234
org.nit.company.name = HCL
org.nit.company.addr = HYB
org.nit.company.size = 10000

# no inline support for map and has-a type property







