spring.application.name=BootMVCProj06-Data-Binding-Form-Binding

#view resolver config
spring.mvc.view.prefix= /WEB-INF/pages/
spring.mvc.view.suffix= .jsp

#embedded server config
server.port=4001

#context path set for embedded server
server.servlet.context-path=/Data-Binding-Form-Binding
