spring.application.name=BootMVCProj01-FirstApp

#Embedded server port no(default port is 8080)
server.port=4041

#Context-path for app in embedded server
server.servlet.context-path=/BootMVCProj01-FirstApp

#ViewResolver input(prefix,sufix) for default InternalResouceViewResolver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
