spring.application.name=BootMVCProj10-Thymeleaf

#embedded server port config
server.port=4041

#context-path config
server.servlet.context-path=/student-mgm-system

#datasource config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql:///sbms

#db config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#profile
spring.profiles.active=local