spring.application.name=BootApp02-Layared-Application
#base file
#activate profile
spring.profiles.active=dev


#JDBC driver  details for  oracle details
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=akshay
spring.datasource.password=akshay
#specify  oracle ucp  datasoruce 
spring.datasource.type=oracle.ucp.jdbc.PoolDataSourceImpl