spring.application.name=BootApp03-ValueAnnotation-SPEL

#Menu prices info
menu.dosarate = 60
menu.idlyrate = 30
menu.poharate = 40
menu.vprate = 50
menu.tea = 15

#hotel info
hotel.name = Amoga Hotel
hotel.addr = Hydrabad
hotel.contactno = 9856234152

#customer info
customer.name = Raja

