spring.application.name=BootMVCProj08-Data-Binding-RequestParam

#view resolver config
spring.mvc.view.prefix= /WEB-INF/pages/
spring.mvc.view.suffix= .jsp

#context path
server.servlet.context-path=/request-param-app

#server port
server.port=4041
