spring.application.name=BootMVCProj07-Two-way-form-data-binding

#View resolver config
spring.mvc.view.prefix= /WEB-INF/pages/
spring.mvc.view.suffix= .jsp

# embedded server port
server.port=4041

#set context path for embedded server
server.servlet.context-path=/two-way-form-binding